#page title
page_title                                : Kiểm tra nồng độ cồn                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1502082080                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1502082080   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /bac-calculator-ios-landing-page/assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Kiểm tra nồng độ cồn                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Miễn phí                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Ứng dụng giúp bạn kiểm tra khi nào lượng cồn trong cơ thể được hấp thụ hoàn toàn.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Quang Phan                                
your_link                                 : https://quangpq.dev                     
your_city                                 : Ho Chi Minh city, Viet Nam                               
email_address                             : pquocquang1102@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : quangphan93
github_username                           : quangpq
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Có nhiều loại rượu để chọn
    description                           : Nhiều loại rượu với các độ cồn khác nhau giúp bạn dễ dàng chọn chính xác lượng cồn đã nạp vào cơ thể.
    fontawesome_icon_name                 : star
    
  - title                                 : Ước lượng thời gian hấp thu cồn
    description                           : Cho biết thời gian cần thiết để cơ thể hấp thụ hàon toàn cồn, giúp bạn quyết định có nên lái xe hay không.
    fontawesome_icon_name                 : star

  - title                                 : Chế độ nền tối
    description                           : Giúp tiết kiệm pin và dễ nhìn vào ban đêm.
    fontawesome_icon_name                 : star

# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.1
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.2

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown